# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gnote < Formula
  desc "A notetaking and snippet sharing application."
  homepage "https://mrinjamul.github.io/gnote"
  version "0.1.1"
  license "MIT License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrinjamul/gnote/releases/download/v0.1.1/gnote_0.1.1_darwin_amd64.tar.gz"
      sha256 "4277a4660a07eab1224bb41cbdd35b9e52c266b08b8599a7454b28eec4a2e030"

      def install
        bin.install "gnote"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrinjamul/gnote/releases/download/v0.1.1/gnote_0.1.1_darwin_arm64.tar.gz"
      sha256 "570ff23330373250a5865f6891282e2709ab6278b08662e6eb671c3cd5f93e46"

      def install
        bin.install "gnote"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrinjamul/gnote/releases/download/v0.1.1/gnote_0.1.1_linux_arm64.tar.gz"
      sha256 "b3e45582590ae245d105a81f73f520dd60a1a8c1f182b0eeab9009deb678748d"

      def install
        bin.install "gnote"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mrinjamul/gnote/releases/download/v0.1.1/gnote_0.1.1_linux_amd64.tar.gz"
      sha256 "1b27076199e0a4d3979e66210be304ab6c89244f400b902e62be12d4d36fc414"

      def install
        bin.install "gnote"
      end
    end
  end
end
