# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MrinjamulCli < Formula
  desc "A CLI to sync domains from local to Cloudflare."
  homepage "https://mrinjamul.github.io/mrinjamul-cli"
  version "1.2.0"
  license "MIT License"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mrinjamul/mrinjamul-cli/releases/download/v1.2.0/mrinjamul-cli_1.2.0_darwin_arm64.tar.gz"
      sha256 "8f65ce66e2c99f66becd9db8d076aa4f4abbbb4e21ad2521d297cbee1889cf15"

      def install
        bin.install "mrinjamul-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mrinjamul/mrinjamul-cli/releases/download/v1.2.0/mrinjamul-cli_1.2.0_darwin_amd64.tar.gz"
      sha256 "e7c5f47fcacc1d4453ab862b965eea245226da62b68b7aecc48134cf1d1b9294"

      def install
        bin.install "mrinjamul-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrinjamul/mrinjamul-cli/releases/download/v1.2.0/mrinjamul-cli_1.2.0_linux_arm64.tar.gz"
      sha256 "c1db3abcf8b02592722d4eb83a91e27bc3851eb279b827f7c1a58fa4d14dbd36"

      def install
        bin.install "mrinjamul-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mrinjamul/mrinjamul-cli/releases/download/v1.2.0/mrinjamul-cli_1.2.0_linux_amd64.tar.gz"
      sha256 "9f0616d52be547fa3814f55aa1c216cae5413bc16d4bb4a676cd82756ea34326"

      def install
        bin.install "mrinjamul-cli"
      end
    end
  end
end
