# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sws < Formula
  desc "A simple (static) web server written in golang"
  homepage "https://github.com/mrinjamul/simple-web-server"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrinjamul/simple-web-server/releases/download/v1.2.0/simple-web-server_1.2.0_darwin_amd64.tar.gz"
      sha256 "b65d77ef207e4d2ff63a22f71f9378ff3b2c71f779501cdd76105c0ca5706500"

      def install
        bin.install "sws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrinjamul/simple-web-server/releases/download/v1.2.0/simple-web-server_1.2.0_darwin_arm64.tar.gz"
      sha256 "77d8d2345d8b18e79616d9eb7533e339c878bab6b4b2d91098370e2232ebcc16"

      def install
        bin.install "sws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mrinjamul/simple-web-server/releases/download/v1.2.0/simple-web-server_1.2.0_linux_amd64.tar.gz"
      sha256 "c53671e987a34fe11979187ddd6b80a8aca15a6a4ebb11f54bb211c1122eea4a"

      def install
        bin.install "sws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrinjamul/simple-web-server/releases/download/v1.2.0/simple-web-server_1.2.0_linux_arm64.tar.gz"
      sha256 "ba02487d19d05bcd025473b01ab6e4977ec1950d874c2f1ac5cacf4183db4c74"

      def install
        bin.install "sws"
      end
    end
  end

  test do
    # Check if the `sws` binary executes and displays the help message
    assert_match "sws", shell_output("#{bin}/sws --version")
  end
end
