# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tasks < Formula
  desc "A simple todoist application"
  homepage "https://github.com/mrinjamul/tasks"
  version "1.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrinjamul/tasks/releases/download/v1.1.1/tasks_1.1.1_darwin_amd64.tar.gz"
      sha256 "00090f1a4e877f17970f2ce60ead00537963b3b730026fb84086566b96e3c212"

      def install
        bin.install "tasks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrinjamul/tasks/releases/download/v1.1.1/tasks_1.1.1_darwin_arm64.tar.gz"
      sha256 "4c140b084f08c10364f31b1772e2717199b9f12c06fb2e5e0fd56646ecd01848"

      def install
        bin.install "tasks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mrinjamul/tasks/releases/download/v1.1.1/tasks_1.1.1_linux_amd64.tar.gz"
      sha256 "c8e055034f74fa26556adbeb6da4194594eb914496383f96972954ce7a17e3f3"

      def install
        bin.install "tasks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrinjamul/tasks/releases/download/v1.1.1/tasks_1.1.1_linux_arm64.tar.gz"
      sha256 "5ed59e7f4b80b6a8f6916670cab0999e2e1a3a43b3760f1df24dba27a4877d02"

      def install
        bin.install "tasks"
      end
    end
  end

  test do
    # Check if the `tasks` binary executes and displays the help message
    assert_match "tasks", shell_output("#{bin}/tasks version")
  end
end
